---
version:  '3.8'
services:
  db:
    image: dbimage:latest
    container_name: db
    ports:
      - "3306:3306"
  auth:
    image: authimage:latest
    container_name: auth_service  
    ports:
      - "5001:5001"
  bookcont:
    image: bookimage:latest
    container_name: book_service
    ports:
      - "5002:5002"
  borrowcont:
    image: borrowimage:latest
    container_name: borrow_service
    ports:
      - "5003:5003"
  frontend:
    image: appimage:latest
    container_name: frontend
    ports:
      - "5000:5000"
  
networks:
  default:
    external:
      name: mynet
    