---
version:  '3.8'
services:
  db:
    image: dbimage:latest
    ports:
      - "3306:3306"
    networks:
      mynet:
        aliases:
          - db
  auth:
    image: authimage:latest
    ports:
      - "5001:5001"
    networks:
      mynet:
        aliases:
          - auth_service
  bookcont:
    image: bookimage:latest
    ports:
      - "5002:5002"
    networks:
      mynet:
        aliases:
          - book_service
  borrowcont:
    image: borrowimage:latest
    ports:
      - "5003:5003"
    networks:
      mynet:
        aliases:
          - borrow_service
  frontend:
    image: appimage:latest
    ports:
      - "5000:5000"
    networks:
      mynet:
        aliases:
          - frontend
  
networks:
  default:
    external:
      name: mynet
    